---
master:
  hosts:
    control01:
      ansible_host: 192.168.0.177
      node_labels:
        - storage.nvme=true
        - storage.ssd=true
        - storage.fast=true
        - storage.usb-flash=true

node_rpi:
  hosts:
    cube02:
      ansible_host: 192.168.0.109
      node_labels:
        - storage.usb-flash=true

    cube03:
      ansible_host: 192.168.0.79
      node_labels:
        - storage.usb-flash=true

node_x86:
  hosts:
    cube04:
      ansible_host: 192.168.0.252
      node_labels:
        - storage.ssd=true
        - storage.fast=true

    # cube05:
    #   ansible_host: 192.168.1.139
    #   node_labels:
    #     - storage.hdd=true

    # cube06:
    #   ansible_host: 192.168.1.191
    #   node_labels:
    #     - storage.hdd=true

rpi:
  children:
    node_rpi:
    master:


x86:
  children:
    node_x86:


node:
  children:
    node_rpi:
    node_x86:


k3s_cluster:
  children:
    master:
    node:
