---
- name: Prepare apt packages
  gather_facts: true
  become: true
  hosts: all
  tasks:
    - name: Install lsb-release package
      ansible.builtin.apt:
        name: lsb-release
        state: present

    - name: Install util-linux-extra package
      ansible.builtin.apt:
        name: util-linux-extra
        state: present

    - name: Install vim package
      ansible.builtin.apt:
        name: vim
        state: present

    - name: Install nfs-common package
      ansible.builtin.apt:
        name: nfs-common
        state: present

    - name: Install open-iscsi package
      ansible.builtin.apt:
        name: open-iscsi
        state: present

    - name: Install iotop package
      ansible.builtin.apt:
        name: iotop
        state: present

    - name: Install curl package
      ansible.builtin.apt:
        name: curl
        state: present

- name: Install Tailscale
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Download Tailscale installation script
      ansible.builtin.get_url:
        url: https://tailscale.com/install.sh
        dest: /tmp/k3s/install_tailscale.sh
        mode: '0755'

    - name: Run Tailscale installation script
      ansible.builtin.command: /tmp/k3s/install_tailscale.sh
      args:
        creates: /usr/sbin/tailscaled
      register: tailscale_install_result
      changed_when: false

    - name: Enable and start tailscaled
      ansible.builtin.systemd:
        name: tailscaled
        enabled: true
        state: started
