---
- name: Prepare apt packages
  gather_facts: true
  become: true
  hosts: all
  tasks:
  - name: Install lsb-release package
    ansible.builtin.apt:
      state: present
      name:
      - lsb-release
      - util-linux-extra
      - vim
      - nfs-common
      - open-iscsi
      - dnsutils
      - curl
      - iotop
      - curl
      - cryptsetup

- name: Install Tailscale
  hosts: all
  gather_facts: true
  become: true
  tasks:
  - name: Create tmp dir
    ansible.builtin.file:
      path: /tmp/k3s
      state: directory

  - name: Download Tailscale installation script
    ansible.builtin.get_url:
      url: https://tailscale.com/install.sh
      dest: /tmp/k3s/install_tailscale.sh
      mode: '0755'

  - name: Run Tailscale installation script
    ansible.builtin.command: /tmp/k3s/install_tailscale.sh
    args:
      creates: /usr/sbin/tailscaled
    register: tailscale_install_result
    changed_when: false

  - name: Enable and start tailscaled
    ansible.builtin.systemd:
      name: tailscaled
      enabled: true
      state: started
